### ISSUE TITLE
Scenario processing: Measures not found in Golden Test File.xml

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#25]
The following measures could not be processed:
- Building1RemovePV
- WholeSiteRemovePV

**Comment by macumber** [comment]
I don't know of an existing measure for this.  This is a removal measure:

`/BuildingSync/Facilities/Facility/Measures/Measure/TypeOfMeasure/Removals/Removal/ExistingSystemRemoved` which references a system `AllThePV` which includes two facilities.  

Basic question to @nllong, should removal measures be implemented as OpenStudio measures so the workflow is:

`BuildingSync with systems -> OSM with systems -> Removal Measure -> OSM without systems` 

or on the BuildingSync file directly

`BuildingSync with systems -> Removal Measure -> BuildingSync without systems -> OSM without systems`

**Comment by nllong** [comment]
@TMaile -- is this still an issue that needs to be addressed?

**Comment by TobiasMaile** [comment]
@nllong yes and no, We do ignore those measures for now and since this file contains two buildings, we never get to measures anyway. I guess we could close this one but address the similar issue for the DC GSA Headquarter file #24.

**Comment by nllong** [comment]
Let’s leave it open and discuss tomorrow.

Da: TobiasMaile <notifications@github.com>
Risposta: BuildingSync/BuildingSync-gem <reply@reply.github.com>
Data: martedì novembre 5 2019 15:24
A: BuildingSync/BuildingSync-gem <BuildingSync-gem@noreply.github.com>
Cc: Nicholas Long <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [BuildingSync/BuildingSync-gem] Scenario processing: Measures not found in Golden Test File.xml (#25)


@nllong<https://github.com/nllong> yes and no, We do ignore those measures for now and since this file contains two buildings, we never get to measures anyway. I guess we could close this one but address the similar issue for the DC GSA Headqwurter file #24<https://github.com/BuildingSync/BuildingSync-gem/issues/24>.

**Comment by TMaile** [comment]
closing this one, since the file never runs due to the two buildings in the file
